---
name: Build artifact on Release

on:
  release:
    types: ["published"]

jobs:
  build:
    name: Build and deploy artifact for amd64 linux
    runs-on: ubuntu-latest
    env:
      CI: "true"
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_DEPLOY_USERNAME }}
      ARTIFACTORY_DEPLOY_TOKEN: ${{ secrets.ARTIFACTORY_DEPLOY_TOKEN }}
      ARTIFACTORY_BASE_URL: ${{ secrets.ARTIFACTORY_BASE_URL }}
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: ''
      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Build weissbot
        run: go build ./cmd/weissbot
      - uses: jfrog/setup-jfrog-cli@v1
      - run: >
          jfrog rt u weissbot "weissbot-generic-prod-local/${VERSION}linux/amd64/"
          --server-id adinb
          --url "$ARTIFACTORY_BASE_URL"
          --user "$ARTIFACTORY_USERNAME"
          --access-token "$ARTIFACTORY_DEPLOY_TOKEN"