---
name: Unit Test on Pull Request to master and development

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - development

jobs:
  lint:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Run unit test
        run: go test ./...
